- playa/exceptions.py
- playa/pdfdocument.py
- playa/pdfpage.py
- tests/test_open.py
- tests/test_pdfdocument.py
> Iteration over the page tree

- playa/converter.py
- playa/data_structures.py
- playa/layout.py
- playa/pdfdevice.py
- playa/pdfdocument.py
- playa/pdfinterp.py
- playa/pdfstructtree.py
- playa/utils.py
- tests/test_pdfstructtree.py
- tests/test_pdftypes.py
- structure tree support
- colour spaces in layout analysis
- MCIDs and tags in layout analysis
- TODO: not translating the origin when mediabox doesn't start at (0,0)
> Add various things desired by pdfplumber

- playa/page.py
This is definitely faster than using reflection 600000 times for each content stream.
> Remove some "flexibility" and build dispatch table for interpreter in __init__

- playa/font.py
- playa/page.py
- playa/utils.py
- pyproject.toml
- tests/test_lazy_api.py
- tests/test_open.py
This is originally a bug in pdfminer.six which I'll report there at some point.  Basically the bounding box for glyphs was being reported as `apply_matrix_pt(bottom_left), apply_matrix_pt(top_right)` which is kind of obviously wrong when the text is rotated.
> Report the actual device space bounding box for rotated text

- benchmarks/converter.py
- playa/document.py
- playa/parser.py
- samples/bogus-stream-length.pdf
- samples/rotated.pdf
- tests/test_lazy_api.py
- tests/test_open.py
Rather serious bug (I believe we call these "security holes") where a stream_length value longer than the actual stream would lead to an endless loop.
> Prevent endless looping on bogus stream length and other EOFs

- playa/parser.py
- tests/test_object_parser.py
It might be good to check what other PDF readers do as the spec is super unclear on this and unfortunately some creators do make inline images with "EI" in the data and no filter...
The spec says there *should* be a newline.  Who wrote that?!?
> Require a newline before EI to fix various inline images

- .github/workflows/tests.yml
- CHANGELOG.md
- TODO.md
- benchmarks/text.py
- playa/ccitt.py
- playa/cmapdb.py
- playa/document.py
- playa/encodingdb.py
- playa/font.py
- pyproject.toml
Largely unnecessary, though a few of them remain...
> Remove most uses of `Typing.cast`

- playa/page.py
Text placement was quite slow for a number of reasons, in particular the desire to correctly report the bounding box of rotated glyphs.
Since 99.999% (very scientific estimate) of glyphs are not rotated this made everything slower and led to actually being slower than pdfminer.six on heavily text-oriented documents.
The "eager" API has not been optimized since it is deprecated.
> Optimize text placement (some dare call it "rendering")

- TODO.md
- playa/ccitt.py
- playa/document.py
- playa/font.py
- playa/page.py
- playa/utils.py
- tests/test_lazy_api.py
> Fix font size and rotated/skewed bounding boxes

- playa/cli.py
- playa/document.py
- playa/page.py
- playa/pdftypes.py
- tests/test_document.py
- tests/test_pdftypes.py
It was a definite problem that the CLI relied on the deprecated `layout` stuff.  Just so nobody gets any ideas here is a breaking change (sorry not sorry)
> fix: deprecate layout in CLI right away and do other useful stuff

- docs/reference.md
- playa/__init__.py
- playa/document.py
- playa/page.py
- playa/parser.py
- playa/pdftypes.py
- playa/worker.py
- tests/test_open.py
- tests/test_parallel.py
This ... doesn't entirely solve the problem of non-serializability, because we don't have a good way to re-connect them in the, er, "manager" process.  But it at least avoids awful surprises for the moment.
> Avoid using (non-serializable) weak references in worker processes

- README.md
- playa/__init__.py
- playa/document.py
- playa/pdftypes.py
- playa/worker.py
- tests/test_document.py
- tests/test_open.py
- tests/test_parallel.py
- tests/test_pdftypes.py
It is *somewhat* of a hack, but not really, unless you have an irrational fear of global variables (news flash: functions, modules, and classes are also global objects).
Basically we just pass the `id` of the parent process' `Document` object to the workers, who just use this integer instead of a weak reference when creating `ObjRef` - it can be serialized when returned, and then we just look it up in a table ... of weak references ... to `Document` objects with worker processes.
~We could of course~ We will in fact just do this for all indirect object references, all the time, ~which might be faster in single-threaded code too.~ which is not slower and also simplifies the code somewhat.
> Enable resolution of indirect object references when using worker processes

- playa/parser.py
- tests/test_object_parser.py
PDF 1.7 sec 7.3.5: The token SOLIDUS (a slash followed by no regular characters) introduces a unique valid name defined by the empty sequence of characters.
> fix: accept empty name objects

- playa/cli.py
- playa/document.py
- playa/page.py
Instead of just printing the characters of text objects, print something useful, a JSON representation of `TextObject` (which will be improved to cover other `ContentObject` as well in PLAYA 0.3)
Also do this in parallel if requested.
> feat: extract text objects not text badly

- playa/page.py
`mcstack` was mutable, meaning that you had to always save a copy of it in order to get the right marked contents for a `ContentObject` outside of iteration context.  This was particularly problematic for PAVÉS' pdfminer.six emulation.
Turns out there isn't really any extra cost in making it a tuple, as it doesn't change very often, so (breaking change...) we do this here.
> feat!: make mcstack immutable to avoid surprises

- README.md
- playa/page.py
This is largely (but not entirely) to support easy visualization in an upcoming PAVÉS.
It doesn't seem to cause any performance hit (after all the references are just tuples of ints) but will use a bit more memory.
> feat: Add backreferences to content objects

- playa/__init__.py
- playa/cli.py
To avoid hideous endless lists import statements such as one experiences when using `pdfminer.six`
> Import and re-export a lot of types at top level

- CHANGELOG.md
- README.md
- benchmarks/text.py
- playa/cli.py
- playa/document.py
- playa/page.py
- tests/test_document.py
Add a few highly useful APIs:
- `Document.is_tagged`: is this a tagged PDF (according to the standard)?
- `Page.flatten`: iterate over all objects, recursing into XObjects, optionally filtering by type (other overloads are possible here in the near future)
- `Page.extract_text`: yes, it finally happened, since it turns out that we beat everybody else except `pypdf` on the benchmarks
> feat: new APIs, flatten, extract_text, is_tagged

- CHANGELOG.md
- playa/document.py
- playa/page.py
- tests/test_document.py
Fix a very atrocious bug that was revealed by pdfannots' test suite (thanks!)
Namely the CTM was not being passed into iteration over Form XObjects, so the child objects ended up with the wrong bboxes.
> Support pdfannots

- CHANGELOG.md
- playa/__init__.py
- playa/document.py
- playa/parser.py
- tests/test_document.py
When iterating over objects in an encrypted with `Document.objects`, the object data wasn't actually being decrypted for top-level indirect objects.
> fix: Decrypt all the things

- CHANGELOG.md
- playa/page.py
- tests/test_lazy_api.py
Yes, `TextObject.bbox` had side effects, that was very bad.
`TextObject.bbox.__iter__` still has side effects for the moment, though at least this is documented.
This also adds useful properties for getting glyph/text object bounds in text space, which should allow us to get bounding quadrilaterals (like docling-parse does)
Finally, it also speeds up `TextObject.bbox` (but not `GlyphObject.bbox`, sadly) by about 20%.
> Remove at least one footgun from `TextObject`

- CHANGELOG.md
- playa/document.py
- playa/font.py
- playa/page.py
- tests/test_open.py
We still need the catch-all for `TypeError` due to rampant use of `dict_value` and friends, but this at least covers some specific and obvious problems.
Also, some broken PDFs use a string instead of a name for `BaseFont`, so we accept that.
And, of course, confusion between `ToUnicode` and `Encoding` reigns supreme, so be tolerant of people who expected some kind of consistency from Adobe based on that bogus tech note and figured that `ToUnicode` could just be a CMap name (it is not a CMap! stop calling it one!)
> Improve error handling in font initialization

- CHANGELOG.md
- playa/page.py
- samples/evil_xobjects.pdf
- tests/data.py
- tests/test_document.py
Opinions differ about what to do about these (some renderers will show "hello world" 3 times, others 2) but consensus is, yeah, infinite recursion is bad.
> fix: do not follow circular xobject references

- playa/cli.py
- playa/data/metadata.py
- playa/structure.py
- samples/hello_structure.pdf
- tests/test_cli.py
- Accept very illegal things in structure tree root, because we can (amazingly, nobody actually does this though)
- Be robust to corrupted PDFs with broken structure elements
> Fix a few annoyances in logical structure trees

- playa/ccitt.py
- playa/cli.py
- playa/cmapdb.py
- playa/data/content.py
- playa/data/metadata.py
- playa/document.py
- playa/font.py
- playa/outline.py
- playa/page.py
- playa/parser.py
- playa/pdftypes.py
- playa/structure.py
- playa/utils.py
- playa/xref.py
- tests/test_lazy_api.py
- tests/test_utils.py
There was a lot of incorrect use of `object` everywhere, now there isnt. Also, points, rects and matrices now are in pdftypes and have their own functions for type-checking them.
> fix!: make type annotations much stricter

- CHANGELOG.md
- playa/__init__.py
- playa/cli.py
- playa/data_structures.py
- playa/document.py
- playa/page.py
- playa/structure.py
- playa/utils.py
- pyproject.toml
- tests/data.py
- tests/test_structure.py
- tests/test_utils.py
BREAKING CHANGE as the `find` and `find_all` now refer to roles (as they do in `pdfplumber`)
Fixes: #97
> feat!: Add support for role map and standard structure types

- CHANGELOG.md
- playa/data/content.py
- playa/page.py
- tests/test_lazy_api.py
This behavior was added in https://github.com/pdfminer/pdfminer.six/commit/e83dd26671e5e6962960ee7b55aa4b8ab45e85d5 with the purpose of detecting rectangles, which is useful for rendering pdf as html. This seems out of scope for playa and adds complexity for nothing.
> Dont't split PathObject into subpaths

- playa/content.py
- playa/data/content.py
- playa/interp.py
- playa/page.py
- playa/structure.py
- samples/graphics_state_in_text_object.pdf
- tests/test_document.py
- tests/test_lazy_api.py
As in some other cases it seems that the pdfminer.six authors were reading the PDF specification a bit too literally, or not literally enough, because there is no earthly reason why most of what was in the `TextState` should not just have gone in the graphics state, aside from the fact that these parameters are described in a different chapter (which is admittedly a bit confusing).  Anyway, the important part is (PDF 2.0 section 9.3.1):
> The text state operators may appear outside text objects, and the values they set are retained across
text objects in a single content stream. Like other graphics state parameters, these parameters shall be
initialised to their default values at the beginning of each page.
It isn't explicitly specified that these parameters get pushed and popped with the …
> refactor!: most of text state is just graphics state

- CHANGELOG.md
- playa/content.py
- playa/data/content.py
- playa/data/metadata.py
- playa/font.py
- samples/text_space.pdf
This isn't complete but it at least isn't blatantly wrong anymore.
BREAKING CHANGE: `text_space_bbox` no longer exists because it isn't actually text space
> Correct documentation and metadata for font, text, and glyph objects

- CHANGELOG.md
- benchmarks/text.py
- playa/content.py
- playa/data/content.py
- playa/font.py
- playa/interp.py
- playa/page.py
- tests/test_lazy_api.py
BREAKING CHANGE: `glyph_offset` property has been removed from the public API, as it was not enormously useful, for the following reasons:
- Real-world PDFs generally do not use the line matrix properly, or abuse it in various ways, such that it is useless for detecting line breaks, *and* the current glyph's relationship to it (which is `glyph_offset`) is not useful for this purpose either.
- Because scaling and fontsize can change through the course of a `BT`/`ET` pair, `glyph_offset` must be represented in so-called "unscaled text space units", which are a confusing and ill-defined concept.  In any case it may not have any immediately obvious relationship to the visual arrangement of glyphs on the page due to subsequent transformations.
Instead, it's possible to efficiently look at the …
> feat!: Improve text extraction and add useful glyph and text properties

- CHANGELOG.md
- docs/reference.md
- playa/font.py
- playa/parser.py
- tests/test_object_parser.py
This *also* fixes some dumb but rare bugs in normal inline images, like we did not accept "Filter" as well as its abbreviation "F".
Fixes: #103
> feat: support PDF 2.0 inline images

- CHANGELOG.md
- playa/document.py
- playa/interp.py
- playa/page.py
- tests/test_document.py
Some caveats in that this is not lazy and may become lazy in the near future.  Using `Mapping` for the type annotation and adding a big fat warning to deter people from thinking it will always be a dict.
> feat: add fonts property (fixes: #86)

- CHANGELOG.md
- benchmarks/structure.py
- playa/cli.py
- playa/content.py
- playa/interp.py
- playa/page.py
- playa/structure.py
- samples/structure_xobjects.pdf
- samples/structure_xobjects_2.pdf
- tests/test_structure.py
- tests/test_text.py
These all go together becaues the marked content improvements are used in text extraction
- Add ability to access structure elements from marked content IDs
- Add ability to access structure element parents from content objects
- Use device space instead of unscaled text space to determine word and line breaks
- Correct the space and line break insertion between marked content sections when extracting text from tagged PDF
Remaining TODOs:
> Fixes and improvements to text extraction, marked content and logical structure

- playa/font.py
- playa/interp.py
- tests/test_fonts.py
Some creators of subset fonts (*cough* LibreOffice) have decided that zero is a helpful value for Ascent and Descent on fonts, for some reason.  Before when we had `get_ascent()` and `get_descent()` methods these were fixed up to use the bbox, and this got removed, oops, causing a regression.
At least now we have a test.
Also the previous code was wrong because it didn't allow for the case where the descent really was zero (ok, yeah, it's supposed to be a *negative* number, not a *non-positive* one, but still).  To be safe we just look for this particular bogus pattern of no-height fonts.
Also this fixes a small error in the `fonts` property on pages and documents which didn't bother to dereference font resource dictionaries, oops.
> fix: correct bogus font descriptors with zero metrics

- playa/cli.py
- playa/image.py
- playa/pdftypes.py
- tests/test_lazy_api.py
mostly just prep work for future refactor, end goal is remove duplicate logic for determining file extension
- all image extraction related code in one file
- `write_jbig2` and `write_pnm` considered internal
> refactor: image extraction

- playa/font.py
- playa/fontprogram.py
- playa/utils.py
probably fringe but i want this...
manually tested by gathering all gids and corresponding text in a pdf and running through [msdf-atlas-gen](https://github.com/Chlumsky/msdf-atlas-gen)
- Type 2, embedded, stream CIDToGIDMap: Dar_smlouva.pdf from https://github.com/mozilla/pdf.js/issues/10519
- Type 2, embedded, /Identity CIDToGIDMap: samples/vertical_writing.pdf
- Type 0, embedded, no CIDFont ops in Top DICT: samples/utf16_tounicode.pdf
- Type 0, embedded, CIDFont ops in Top DICT: example needed
- Type 0, external: example needed
> feat: cid2gid for CIDFont

- playa/utils.py
- tests/test_utils.py
We should never crash when trying to decode a "text string" even if the encoding is obviously nonsense!
fixes: #153
> fix: always decode text (fixes: #153)

- playa/parser.py
- tests/test_object_parser.py
Ugh! Someone (me) did not read the standard closely enough!  Trailing periods are definitely allowed in numbers.
Fixes: #151
> fix: accept all standard number syntaxes (oops)

- CHANGELOG.md
- playa/document.py
- playa/parser.py
- playa/xref.py
- samples/contrib/issue-146-broken-xref-and-streams.pdf
- tests/test_object_parser.py
Fixes #146 which is a PDF with a *lot* of problems:
- `startxref` isn't delimited by newlines like it should be
- the limits of the xref table aren't delimited by newlines either
- there's a reference to indirect object 0 which cannot exist
- all of the streams are terminated with `endstrea` instead of `endstream`
It is possible to be robust to all that.  Also this fixes a horrible, no good bug that I introduced in the fallback indirect object reference parsing where the arguments were reversed to `_getobj_parse_approx`, meaning that fallback indirect object reference parsing just never worked, ever.
> Be robust to multiply broken PDFS (xrefs, streams, indirect objects)

- .flake8
- CHANGELOG.md
- README.md
- benchmarks/marked_content.py
- playa/cli.py
- playa/content.py
- playa/data/metadata.py
- playa/document.py
- playa/interp.py
- playa/page.py
- playa/structure.py
- playa/utils.py
- tests/test_pdftypes.py
- tests/test_structure.py
By caching marked content sections we get reasonable performance (I might make this Lazier in the future).
We now also return a `PageStructure` instead of a list for `page.structure` and `xobj.structure`, which has convenient methods to search up the parent tree to find enclosing elements (like tables for instance).
Add structure attributes and classes, but note, we don't try to do any overriding or interpretation unlike my ill-considered pdfplumber code.  This does mean that `--structure` in the CLI gets a bit slower as it has more stuff to output.
Also, finally use `asobj` directly in `--structure` in the CLI rather than a custom serializtion.
> Greatly accelerate and improve logical structure tasks

- .github/workflows/tests.yml
- playa/cmapdb.py
- playa/fontprogram.py
- playa/page.py
- playa/worker.py
Whoops!  We weren't actually compatible with Python 3.8 (yes, it is end of life, but since we went to the trouble to use all those old-style type annotations, we might as well keep supporting it!)
> fix: restore python 3.8 compatibility
