playa/cmapdb.py
playa/pdffont.py
playa/pdfinterp.py
playa/pdfparser.py
playa/psparser.py
tests/benchmark_parser.py
tests/test_open.py
tests/test_pdfparser.py

Now we are definitively faster than the previous code!  And this can be submitted as a PR to pdfminer.six as well.

Implement in-memory parsing

---

playa/pdfparser.py
playa/psparser.py
tests/benchmark_parser.py
tests/test_pdfminer_psparser.py

Wow the PDF standard has some real junk in it!

Use `mmap` when possible to parse and fix various small bugs

---

README.md
playa/color.py
playa/page.py
playa/structtree.py
playa/utils.py
tests/benchmark_convert.py
tests/benchmark_parser.py
tests/test_lazy_api.py

Implement the "lazy" API as (mostly) detailed in the README.
This still needs some testing and optimization as if you expand all the things, it is a bit slower than the "eager" API (but still faster than pdfminer).

Implement lazy API

---

playa/cli.py
playa/page.py
samples/contrib/issue-1059-cmap-decode.pdf

Also a `--debug` flag for the CLI for debugging.

Verify that we don't have pdfminer.six#1059 (and warn about it)

---

playa/cmapdb.py
playa/document.py
playa/font.py
playa/page.py
tests/test_cmapdb.py
tests/test_lazy_api.py

Optimize cmaps

---

README.md
benchmarks/converter.py
benchmarks/parallel.py
benchmarks/parallel_miner.py
benchmarks/parser.py
playa/__init__.py
playa/document.py
tests/data.py
tests/test_parallel.py

Support parallel operations over pages

---

TODO.md
playa/document.py
tests/test_document.py

feat: support slices and tuples in page list

---

playa/cmapdb.py
playa/font.py

Also clarify that things are **not CIDs** in some places and **not UTF-16** in others.

Optimize text extraction a bit more

---

README.md
playa/cli.py

yes we do text now.  not particularly fast, but spectacularly faster than pdfminer.six!

feat: support text extraction and make a benchmark

---

CHANGELOG.md
docs/reference.md
playa/__init__.py
playa/document.py
playa/outline.py
playa/structure.py
tests/test_document.py
tests/test_outline.py

Make them lazier (not necessarily faster) and also preserve the tree structure of the outline so the user doesn't have to recreate it afterwards (seriously)

New document outline and destination APIs

---

docs/reference.md
playa/__init__.py
playa/document.py
playa/outline.py
playa/worker.py
tests/test_document.py
tests/test_parallel.py

Like the title says!  Fixes #63 (hopefully)

feat: accept `bytes` as input (for async applications)

---

playa/ascii85.py
playa/cmapdb.py
playa/color.py
playa/document.py
playa/outline.py
playa/page.py
playa/parser.py
playa/xref.py
tests/data.py
tests/test_cmapdb.py
tests/test_lazy_api.py
tests/test_object_parser.py
tests/test_outline.py

We weren't running the ones that were download links, which include yet another weird and wonderful set of broken PDFs.  So, this should add some extra robustness (I hope).

Run **all** the pdf.js tests and fix as many problems as possible

---

CHANGELOG.md
playa/security.py
tests/test_crypto.py

Remove padding in AES encrypted strings

---

CHANGELOG.md
playa/__init__.py
playa/content.py
playa/data/__init__.py
playa/data/content.py
playa/interp.py
playa/page.py
playa/structure.py
tests/test_lazy_api.py

Not really, but it no longer exists in the public API

refactor!: drown text state in the bathtub

---

playa/content.py

leftover from https://github.com/dhdaines/playa/pull/87 part 1

Fix text rendering matrix for GlyphObject

---

playa/page.py
tests/test_document.py

feat: support bbox on Annotation (oops)

---

playa/color.py
playa/content.py
playa/data/content.py
playa/interp.py
playa/pdftypes.py
samples/extgstate.pdf
tests/test_document.py

No idea if this is correct and no idea how to test this...

Implement do_gs

---

CHANGELOG.md
playa/page.py
tests/test_document.py

This requires some duplication of code but it's for a good cause

Iterate over Form XObjects inside Form XObjects with `.xobjects`

---

playa/content.py
playa/font.py
playa/interp.py
tests/test_fonts.py
tests/test_lazy_api.py

Allow iteration over Type3 font programs

---

CHANGELOG.md
README.md
playa/cli.py
playa/interp.py

Makes them slightly more useful.  Still need to do soft masks, masks, alternates, that is for 0.6.1.

Extract images as PNMs if possible

---

playa/cli.py
playa/pdftypes.py
tests/test_lazy_api.py

fix: avoid writing empty image files

---

playa/cli.py
playa/content.py
playa/font.py
playa/page.py
tests/test_cli.py

closes https://github.com/dhdaines/playa/issues/133

feat: fontfile extraction

---

playa/image.py

an example image can be found at https://github.com/pdfminer/pdfminer.six/issues/795
Note that this will incorrectly extract images with unsupported colorspace when the number of components is 1 or 3, but arguably extracting any image at all, even in wrong colors, is better than extracting raw bytes

extract images with cie based colorspace

---

CHANGELOG.md
README.md
playa/content.py
tests/test_lazy_api.py

If we're going to make the graphics state mutable then we need this.
Also verify that the resulting objects really are finalized (this may not be possible to test completely!)

feat: Add finalize() method to ContentObject
